### ISSUE TITLE
update js adblocker

### ISSUE THREAD

**Issue by hazemAzzam** [SafwanLjd/PyEgyBest#4]
Hello, Thanks for your work, but Egybest now blocks the requests, can you update it ?

**Comment by LoaiDev** [comment]
same problem here. is this project still active?

**Comment by SafwanLjd** [comment]
I am aware that the library doesn't work anymore; however I've lost interest in the project, so I don't think I'm going to attempt to fix it anytime soon. Feel free to fork it though.

**Comment by SafwanLjd** [comment]
This project has been officially discontinued, so I'm going to close this issue.
